services:
  aequa-node-0:
    build: .
    image: aequa-local:latest
    container_name: aequa-node-0
    command: ["--validator-api","0.0.0.0:4600","--monitoring","0.0.0.0:4620"]
    ports:
      - "4600:4600"
      - "4610:4610"
      - "4615:4615"
      - "4620:4620"
  aequa-node-1:
    image: aequa-local:latest
    container_name: aequa-node-1
    command: ["--validator-api","0.0.0.0:4600","--monitoring","0.0.0.0:4620"]
    ports:
      - "4601:4600"
      - "4611:4610"
      - "4616:4615"
      - "4621:4620"
  aequa-node-2:
    image: aequa-local:latest
    container_name: aequa-node-2
    command: ["--validator-api","0.0.0.0:4600","--monitoring","0.0.0.0:4620"]
    ports:
      - "4602:4600"
      - "4612:4610"
      - "4617:4615"
      - "4622:4620"
  aequa-node-3:
    image: aequa-local:latest
    container_name: aequa-node-3
    command: ["--validator-api","0.0.0.0:4600","--monitoring","0.0.0.0:4620"]
    ports:
      - "4603:4600"
      - "4613:4610"
      - "4618:4615"
      - "4623:4620"

  adversary-agent:
    build:
      context: .
      dockerfile: Dockerfile.attacker
    image: aequa-attacker:latest
    container_name: adversary-agent
    environment:
      ENDPOINTS_QBFT: "http://aequa-node-0:4610,http://aequa-node-1:4610,http://aequa-node-2:4610,http://aequa-node-3:4610"
      ENDPOINTS_P2P: "http://aequa-node-0:4615,http://aequa-node-1:4615,http://aequa-node-2:4615,http://aequa-node-3:4615"
      P2P_ID_PREFIX: "X"
      P2P_MAX_IDS: "1024"
    depends_on:
      - aequa-node-0
      - aequa-node-1
      - aequa-node-2
      - aequa-node-3
    restart: unless-stopped

  netem-0:
    image: alpine:3
    container_name: netem-0
    network_mode: "service:aequa-node-0"
    cap_add:
      - NET_ADMIN
    command: ["sh","-c","sleep infinity"]
    depends_on: [aequa-node-0]
  netem-1:
    image: alpine:3
    container_name: netem-1
    network_mode: "service:aequa-node-1"
    cap_add:
      - NET_ADMIN
    command: ["sh","-c","sleep infinity"]
    depends_on: [aequa-node-1]
  netem-2:
    image: alpine:3
    container_name: netem-2
    network_mode: "service:aequa-node-2"
    cap_add:
      - NET_ADMIN
    command: ["sh","-c","sleep infinity"]
    depends_on: [aequa-node-2]
  netem-3:
    image: alpine:3
    container_name: netem-3
    network_mode: "service:aequa-node-3"
    cap_add:
      - NET_ADMIN
    command: ["sh","-c","sleep infinity"]
    depends_on: [aequa-node-3]

