name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  contents: read
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  verify-bom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check UTF-8 BOM not present in .go files
        shell: bash
        run: |
          set -euo pipefail
          err=0
          while IFS= read -r -d '' f; do
            if grep -Iq $'\xEF\xBB\xBF' "$f"; then
              echo "::error file=$f::BOM found"
              err=1
            fi
          done < <(git ls-files -z '*.go')
          test $err -eq 0
  lint:
    runs-on: ubuntu-latest
    needs: [verify-bom]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          args: --timeout=5m
  build-test:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Build
        run: go build ./cmd/dvt-node
      - name: Unit tests with coverage
        run: go test ./internal/api -coverprofile=coverage.out -covermode=atomic
      - name: Print coverage summary
        run: go tool cover -func=coverage.out
      - name: Enforce coverage threshold
        env:
          COVERAGE_MIN: ${{ vars.COVERAGE_MIN }}
        run: |
          set -euo pipefail
          total=$(go tool cover -func=coverage.out | awk '/total:/ {print $3}')
          pct=${total%*%}
          thr_env=${COVERAGE_MIN:-70}
          thr=$(awk -v e="$thr_env" 'BEGIN{t=e+0; if (t<70) t=70; print t}')
          echo "coverage=$pct% (threshold=$thr%)"
          awk -v p=$pct -v t=$thr 'BEGIN{ exit (p+0 < t+0) ? 1 : 0 }'
      - name: Govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: '1.24'
          work-dir: .

  qbft-tests:
    # Non-required visibility job to exercise qbft package tests
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Run qbft package tests (non-required)
        run: |
          set -euo pipefail
          go test ./internal/consensus/qbft -count=1
  security-snyk:
    runs-on: ubuntu-latest
    needs: [build-test]
    # Run on internal PRs (non-fork) and on main branch pushes
    if: (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) || github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Install Snyk CLI
        uses: snyk/actions/setup@v1
      - name: Snyk auth
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        shell: bash
        run: |
          set -euo pipefail
          if [ -z "$SNYK_TOKEN" ]; then
            echo "::error::Missing SNYK_TOKEN secret. Configure repository secret SNYK_TOKEN.";
            exit 1
          fi
          snyk auth "$SNYK_TOKEN"
      - name: Snyk test (retry up to 3)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        shell: bash
        run: |
          set -euo pipefail
          for i in 1 2 3; do
            if snyk test --all-projects --severity-threshold=high --fail-on=all --prune-repeated-subdependencies; then
              exit 0
            fi
            echo "Snyk test failed on attempt $i"
            if [ "$i" -eq 3 ]; then
              exit 1
            fi
            sleep $((i*15))
          done
      - name: Snyk monitor (main only)
        if: github.ref == 'refs/heads/main'
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        shell: bash
        run: |
          set -euo pipefail
          snyk monitor --all-projects --prune-repeated-subdependencies
